### PR TITLE
Update README & License

### PR DESCRIPTION
**Pull request by ra1028**

### CODE REVIEW

**Comment by Sameesunkaria** [comment]
Just curious about the license change...

**Comment by ra1028** [comment]
@Sameesunkaria 
There is no valid reason, it just matches my new library [Carbon](https://github.com/ra1028/Carbon).
Is it better to remain MIT license?

**Comment by Sameesunkaria** [comment]
@ra1028 I guess it just a personal preference thing, but I like the extra little bit of freedom that the MIT License grants us. But, if you wanna move to Apache, go ahead! I was just curious.

**Comment by ra1028** [comment]
@Sameesunkaria 
I'm not familiar with licensing, but I think that the Apache 2.0 license is a sufficiently freedom and that more people can use it with confidence.
I move forward, but if you have opinions please don't hesitate to say. DifferenceKit is made by the community including you.

**Pull request merged**
