### PR TITLE
Setting in info.plist does not support dark mode

### PR DESCRIPTION
**Pull request by saucym**
## Checklist
- [x] All tests are passed.  
- [ ] Added tests.  
- [x] Documented the code using [Xcode markup](https://developer.apple.com/library/mac/documentation/Xcode/Reference/xcode_markup_formatting_ref).  
- [x] Searched [existing pull requests](https://github.com/ra1028/DifferenceKit/pulls) for ensure not duplicated.

### CODE REVIEW

**Comment by ra1028** [comment]
Hi @saucym ,

Thanks for the PR.
But, I don't prefer these changes, because the automatic animation is not suitable for the default behavior.

**Comment by saucym** [comment]
> Hi @saucym ,
> 
> Thanks for the PR.
> But, I don't prefer these changes, because the automatic animation is not suitable for the default behavior.

Ok, it's also good now.
The current case is abnormal in Diablo mode. Disabled in the info.plist file.

**Comment by saucym** [comment]
> Hi @saucym ,
> 
> Thanks for the PR.
> But, I don't prefer these changes, because the automatic animation is not suitable for the default behavior.

Ok, it's also good now.
The current examples is abnormal in dark mode. Disabled in the info.plist file.

**Comment by ra1028** [comment]
@saucym 
Sorry for my late reply.
Thanks!

**Pull request merged**
