### PR TITLE
Add completion blocks for UIKit batch update methods

### PR DESCRIPTION
**Pull request by subtranix**
## Checklist
- [ ] All tests are passed.  
- [ ] Added tests.  
- [x] Documented the code using [Xcode markup](https://developer.apple.com/library/mac/documentation/Xcode/Reference/xcode_markup_formatting_ref).  
- [x] Searched [existing pull requests](https://github.com/ra1028/DifferenceKit/pulls) for ensure not duplicated.

### CODE REVIEW

**Comment by che1404** [comment]
Hello! I'm interested in this change. Is there any reason why this PR was closed without comment?
Thanks!

**Comment by subtranix** [comment]
> Hello! I'm interested in this change. Is there any reason why this PR was closed without comment?
> Thanks!

Hi! I noticed that the completion in performBatchUpdates works unstable, it may be called or not for no reason. So I decided not to use it, and went with totally different solution for my app

**Comment by che1404** [comment]
Hello @subtranix , I'm wondering what solution did you use in order to know when the batch updates have finished :)

**Comment by subtranix** [comment]
I refused the idea to bind logic to updates completion )

**Pull request closed without merging**
