### PR TITLE
Add protocols to allow mocking UITableView and UICollectionView

### PR DESCRIPTION
**Pull request by benasher44**
We're going to switch to using `DifferenceKit` in plangrid/ReactiveLists#136. However, we're running into issues related to our unit tests. To help fix this, this PR adds the `TableView` and `CollectionView` protocols, which will allow our upstream library to write tests that use `DifferenceKit` without actually interacting with real `UITableView` and `UICollectionView` instances.

### CODE REVIEW

**Comment by benasher44** [comment]
For existing users of `DifferenceKit`, this should have no impact because the conformances to the protocols for `UITableView` and `UICollectionView` come with this change.

**Comment by Sameesunkaria** [comment]
I'm not sure I understand the problem this is solving. If you are wanting to perform integration tests with DifferenceKit, then using the actual instances of UITableView and UICollectionView is the way to go (because that is where you are going to find any crashes related to incorrect diffing). 

Other than that, I'm don't think the unit tests should even know about how the diffing is being performed, just that the final result is correct. But, we have tests built right into DifferenceKit for that.

This is also polluting the general namespace with what is a very generic name for a protocol, `TableView` and `CollectionView`.

**Comment by benasher44** [comment]
> Other than that, I'm don't think the unit tests should even know about how the diffing is being performed, just that the final result is correct. But, we have tests built right into DifferenceKit for that.

I completely agree, so I'll elaborate. We want to be able to test if we called the `DifferenceKit` `reload` UIKit extension method or not. To do this in our tests, we have to use the concrete UIKit types because 
that's where they're defined. By adding these protocols, we can intercept that call. I'm open to other ways of doing this, but this is an approach I've taken in the past.

> This is also polluting the general namespace with what is a very generic name for a protocol, TableView and CollectionView.

These protocols will be under the `DifferenceKit` namespace. Are you concerned about the names in general? I could add `Protocol` as a suffix. I could also change them to `DifferentiableTableView` and `DifferentiableCollectionView`.

**Comment by benasher44** [comment]
Hm actually we can just make a protocol that has `reload` within our own lib. I'm going to close this until I see that option through.

**Pull request closed without merging**
