### PR TITLE
v0.3.0

### PR DESCRIPTION
**Pull request by ra1028**
# Version 0.3.0

## Breaking changes
- `Differentiable.differenceIdentifier` is now renamed to `identifier`.
- `Differentiable.isUpdated(from:)` is now meaning reversed, name has become `isContentEqual(to:)`.

### CODE REVIEW

**Comment by Sameesunkaria** [comment]
Hi @ra1028 ! 👋🏻

Really loving the work you have done to bring DifferenceKit to life. I just have one concern with this update; `identifier` is a very generic name for a property, and is often used in many code bases. This makes it so that we would have to rename our previously existing property to conform to Differentiable, if we did not want to use the old identifier as a difference identifier.

I believe that `differenceIdentifier` was a nicer name for the property, and helps the reader easily understand that it is being used for diffing calculations.

**Comment by insidegui** [comment]
I have the same concern as @Sameesunkaria

**Comment by ra1028** [comment]
@Sameesunkaria @insidegui 
Oh, agreed 👍 
I'll turn back the name of identifier to `differenceIdentifier` in next release.

**Comment by ra1028** [comment]
@Sameesunkaria @insidegui 
I released it in new version [0.4.0](https://github.com/ra1028/DifferenceKit/releases/tag/0.4.0) 👍

**Pull request merged**
